[phases.setup]
# Gunakan nama paket Nix yang valid
nixPkgs = ["php", "phpExtensions.pdo_mysql", "phpComposer", "nodejs", "yarn"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"