[phases.setup]
# Paket Nix yang tersedia:
# - php
# - phpExtensions.pdo_mysql
# - nodejs
# - yarn
# - composer (global)
nixPkgs = ["php" "phpExtensions.pdo_mysql" "nodejs" "yarn" "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"